import type { Level } from '@/types';

export const LEVELS: Level[] = [
  {
    levelId: 1,
    name: '初识算术',
    difficulty: 1,
    questionTypes: ['addition'],
    questionCount: 10,
    timeLimit: 120,
    starThresholds: [60, 80, 95],
    coinReward: 50,
    rewardCoins: 50,
    unlocked: true,
    completed: false,
    stars: 0,
    bestScore: 0,
    bestAccuracy: 0,
    description: '学习简单的加法运算，开启你的数学之旅！',
    icon: '🌟'
  },
  {
    levelId: 2,
    name: '减法入门',
    difficulty: 1,
    questionTypes: ['subtraction'],
    questionCount: 10,
    timeLimit: 120,
    starThresholds: [60, 80, 95],
    coinReward: 50,
    rewardCoins: 50,
    unlocked: false,
    completed: false,
    stars: 0,
    bestScore: 0,
    bestAccuracy: 0,
    description: '掌握减法运算，看看你能拿走多少苹果！',
    icon: '🍎'
  },
  {
    levelId: 3,
    name: '加减混合',
    difficulty: 2,
    questionTypes: ['addition', 'subtraction'],
    questionCount: 12,
    timeLimit: 120,
    starThresholds: [65, 85, 95],
    coinReward: 60,
    rewardCoins: 60,
    unlocked: false,
    completed: false,
    stars: 0,
    bestScore: 0,
    bestAccuracy: 0,
    description: '加法和减法一起来，挑战你的反应速度！',
    icon: '⚡'
  },
  {
    levelId: 4,
    name: '比一比',
    difficulty: 2,
    questionTypes: ['comparison'],
    questionCount: 12,
    timeLimit: 90,
    starThresholds: [70, 85, 95],
    coinReward: 60,
    rewardCoins: 60,
    unlocked: false,
    completed: false,
    stars: 0,
    bestScore: 0,
    bestAccuracy: 0,
    description: '比较数字大小，找出最大的那个！',
    icon: '🔍'
  },
  {
    levelId: 5,
    name: '乘法口诀',
    difficulty: 3,
    questionTypes: ['multiplication'],
    questionCount: 15,
    timeLimit: 150,
    starThresholds: [70, 85, 95],
    coinReward: 80,
    rewardCoins: 80,
    unlocked: false,
    completed: false,
    stars: 0,
    bestScore: 0,
    bestAccuracy: 0,
    description: '学习乘法运算，挑战九九乘法表！',
    icon: '✖️'
  },
  {
    levelId: 6,
    name: '除法小能手',
    difficulty: 3,
    questionTypes: ['division'],
    questionCount: 15,
    timeLimit: 150,
    starThresholds: [70, 85, 95],
    coinReward: 80,
    rewardCoins: 80,
    unlocked: false,
    completed: false,
    stars: 0,
    bestScore: 0,
    bestAccuracy: 0,
    description: '学习除法运算，公平分配物品！',
    icon: '➗'
  },
  {
    levelId: 7,
    name: '找规律',
    difficulty: 4,
    questionTypes: ['pattern'],
    questionCount: 12,
    timeLimit: 180,
    starThresholds: [65, 80, 90],
    coinReward: 100,
    rewardCoins: 100,
    unlocked: false,
    completed: false,
    stars: 0,
    bestScore: 0,
    bestAccuracy: 0,
    description: '发现数字的规律，培养逻辑思维！',
    icon: '🔮'
  },
  {
    levelId: 8,
    name: '补全算式',
    difficulty: 4,
    questionTypes: ['completion'],
    questionCount: 12,
    timeLimit: 180,
    starThresholds: [65, 80, 90],
    coinReward: 100,
    rewardCoins: 100,
    unlocked: false,
    completed: false,
    stars: 0,
    bestScore: 0,
    bestAccuracy: 0,
    description: '填入正确的数字或符号，使等式成立！',
    icon: '🧩'
  },
  {
    levelId: 9,
    name: '四则运算',
    difficulty: 5,
    questionTypes: ['addition', 'subtraction', 'multiplication', 'division'],
    questionCount: 18,
    timeLimit: 180,
    starThresholds: [70, 85, 95],
    coinReward: 120,
    rewardCoins: 120,
    unlocked: false,
    completed: false,
    stars: 0,
    bestScore: 0,
    bestAccuracy: 0,
    description: '加减乘除混合运算，考验你的综合能力！',
    icon: '🎯'
  },
  {
    levelId: 10,
    name: '数学大师',
    difficulty: 6,
    questionTypes: ['addition', 'subtraction', 'multiplication', 'division', 'comparison', 'pattern', 'completion'],
    questionCount: 20,
    timeLimit: 240,
    starThresholds: [75, 85, 95],
    coinReward: 200,
    rewardCoins: 200,
    unlocked: false,
    completed: false,
    stars: 0,
    bestScore: 0,
    bestAccuracy: 0,
    description: '终极挑战！成为真正的数学大师！',
    icon: '👑'
  },
  {
    levelId: 11,
    name: '速算高手',
    difficulty: 7,
    questionTypes: ['addition', 'subtraction', 'multiplication', 'division'],
    questionCount: 25,
    timeLimit: 150,
    starThresholds: [80, 90, 98],
    coinReward: 250,
    rewardCoins: 250,
    unlocked: false,
    completed: false,
    stars: 0,
    bestScore: 0,
    bestAccuracy: 0,
    description: '在限定时间内完成尽可能多的题目！',
    icon: '⏱️'
  },
  {
    levelId: 12,
    name: '逻辑挑战',
    difficulty: 8,
    questionTypes: ['pattern', 'completion', 'comparison'],
    questionCount: 15,
    timeLimit: 200,
    starThresholds: [75, 85, 95],
    coinReward: 300,
    rewardCoins: 300,
    unlocked: false,
    completed: false,
    stars: 0,
    bestScore: 0,
    bestAccuracy: 0,
    description: '逻辑思维的终极考验！',
    icon: '🧠'
  }
];

export const TOTAL_LEVELS = LEVELS.length;

export const getLevelById = (levelId: number): Level | undefined => {
  return LEVELS.find(level => level.levelId === levelId);
};

export const getUnlockedLevels = (currentLevel: number): Level[] => {
  return LEVELS.map(level => ({
    ...level,
    unlocked: level.levelId <= currentLevel + 1
  }));
};
